[project]
name = "immaterialdb"
version = "0.1.13"
description = "A materialized graph based dynamodb client"
authors = [{ name = "James Brock", email = "contact@dysomni.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "boto3",
  "pydantic>=2,<3",
  "ulid-py",
  "moto>=5,<6",
  "boto3-stubs[dynamodb]",
]

[tool.setuptools.packages.find]
include = ["immaterialdb*"]

[tool.black]
line-length = 120

[dependency-groups]
dev = [
  "moto>=5,<6",
  "pytest",
  "ipykernel",
  "ipython",
  "boto3-stubs[dynamodb, s3, boto3]",
  "freezegun",
  "black>=25.1.0",
  "pytest-cov>=6.1.1",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
